AH/urls.py
from django.conf.urls import url
from AH import views


urlpatterns = [
               url(r'^$', views.AH, name='AH'),
]

JoeanLiu/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weapon/', include('weapon.urls', namespace='weapon')),
    url(r'^tank/', include('tank.urls', namespace='tank')),
    url(r'^attackhelicopter/', include('attackhelicopter.urls', namespace='attackhelicopter')),
    url(r'^AH/',include('AH.urls',namespace='AH')),
    url(r'^.*', include('weapon.urls')),
]

attackhelicopter/urls.py
from django.conf.urls import url
from attackhelicopter import views

urlpatterns = [
               url(r'^$', views.attackhelicopter, name='attackhelicopter'),
]

tank/urls.py
from django.conf.urls import url
from tank import views

urlpatterns = [
                   url(r'^category/(?P<categoryID>[0-9]+)/$', views.category, name='category'),
                   url(r'^addCategory/$', views.addCategory, name='addCategory'),
                   url(r'^addPage/(?P<categoryID>[0-9]+)/$', views.addPage, name='addPage'),
                   url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory, name='deleteCategory'),
                   url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage, name='deletePage'),
                   url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory,name='updateCategory'),
                   url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage, name='updatePage'),
                   url(r'^$', views.tank, name='tank'),

]

weapon/urls.py
from django.conf.urls import url
from weapon import views

urlpatterns = [
               url(r'^$', views.weapon, name='weapon'),
               ]

AH/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('-likes',)
 
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-views',)

attackhelicopter/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

tank/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('-likes',)
 
class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-views',)

weapon/models.py
from django.db import models

tank/forms.py
from django import forms
from tank.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label='戰車名稱', help_text='(請輸入戰車名稱)')
    class Meta:
        model = Category
        fields = ('name', )

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='網頁標題')
    url = forms.URLField(max_length=128, label='網頁網址')
    class Meta:
        model = Page
        exclude = ('category', 'views')

AH/views.py
from django.shortcuts import render


def AH(request):
     return  render(request,  'AH/AH.html')

attackhelicopter/views.py
from django.shortcuts import render

def attackhelicopter(request):
            context = {'like':'戰鬥直昇機', }
            return render(request, 'attackhelicopter/attackhelicopter.html', context)

main/views.py
from django.shortcuts import render

# Create your views here.

tank/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from tank.models import Category, Page
from tank.forms import CategoryForm, PageForm


def tank(request):
        categories = Category.objects.all()
        context = {'categories':categories}
        return render(request, 'tank/tank.html', context)
    
def category(request, categoryID):
    context = {}
    try:
        category = Category.objects.get(id=categoryID)
        context['category'] = category
        context['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
        pass
    return render(request, 'tank/category.html', context)

def addCategory(request):
    template = 'tank/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    #request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('tank:tank'))
    # Or try this: return tank(request) 
def addPage(request, categoryID):
    template = 'tank/addPage.html'
    try:
        pageCategory = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return category(request, categoryID)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('tank:category', args=(categoryID, )))
    
def deleteCategory(request, categoryID):
    if request.method!='POST':
        return tank(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('tank:tank'))

def deletePage(request, pageID):
    if request.method!='POST':
        return tank(request)
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryID = pageToDelete.category.id
        pageToDelete.delete()
    else:
        categoryID = ''
    return redirect(reverse('tank:category', args=(categoryID, )))
 

def updateCategory(request, categoryID):
    template = 'tank/updateCategory.html'
    try:
        category = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return tank(request)
    if request.method=='GET':
        form = CategoryForm(instance=category)
        return render(request, template, {'form':form, 'category':category})
    # request.method=='POST'
    form = CategoryForm(request.POST, instance=category)
    if not form.is_valid():
        return render(request, template, {'form':form, 'category':category})
    form.save()
    return redirect(reverse('tank:tank'))

def updatePage(request, pageID):
    template = 'tank/updatePage.html'
    try:
        page = Page.objects.get(id=pageID)
    except Page.DoesNotExist:
        return category(request, '')
    if request.method=='GET':
        form = PageForm(instance=page)
        return render(request, template, {'form':form, 'page':page})
     # request.method=='POST'
    form = PageForm(request.POST, instance=page)
    if not form.is_valid():
        return render(request, template, {'form':form, 'page':page})
    form.save()
    return redirect(reverse('tank:category', args=(page.category.id,)))

def clean(self):
    cleanedData = self.cleaned_data
    url = cleanedData.get('url')
    if url and not url.startswith('http://'):
        url = 'http://' + url
        cleanedData['url'] = url
    return cleanedData

weapon/views.py
from django.http import HttpResponse
from django.shortcuts import render
import datetime


def weapon(request):
        now = datetime.datetime.now()
        context = {'like':'武器小百科',  'now':now}
        return render(request, 'weapon/weapon.html', context)
# Create your views here.

AH/templates/AH/AH.html
<!doctype html>
<html>
<head>
<meta charset=utf-8>
</head>
<body>
<h1>戰鬥直昇機小百科</h1>
</body>
</html>

tank/templates/tank/addCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>戰車小百科</title>
<meta charset=utf-8>
</head>
<body>
<h1>新增戰車分類</h1>
<form method=post action={% url 'tank:addCategory' %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<br>
<p><a href={% url 'tank:tank' %}>回 Tank 網頁</a></p>
</body>
</html>

tank/templates/tank/addPage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
</head>
<body>
<h1>在{{category.name}}分類中新增一筆網頁</h1>
<form method=post action={% url 'tank:addPage' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'tank:category' category.id %}>回{{category.name}}網頁
</a></p>
</body>
</html>

tank/templates/tank/category.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>戰車小百科</title>
<meta charset=utf-8>
</head>
<body>

{% if category %}
 <h1>{{category.name}}</h1>
 {% if pages %}
 	<table>
 		<tr><th>戰車名稱</th></tr>
 		{% for page in pages %}
 		<tr>
 			<td>
			 <a href={{page.url}}>{{page.title}}</a>
 			</td>
 			<td>
 				<form action={% url 'tank:updatePage' page.id %}>
 					<input type=submit value=修改>
 				</form>
 			</td>
 			<td>
 				<form method=post action={% url 'tank:deletePage' page.id %}>
 					{% csrf_token %}
 					<input type=submit value=刪除>
 				</form>
 			</td> 
 		</tr>
 		{% endfor %}
 	</table>
 {% else %}
 	<p><strong>此分類目前並無網頁。</strong></p>
 {% endif %}
 <br>
 <p><a href={% url 'tank:addPage' category.id %}>新增網頁</a></p>
{% else %}
 <p>所指定的分類「{{categoryID}}」不存在。</p>
{% endif %}
<p><a href={% url 'tank:tank' %}>回 Tank 網頁</a></p>

</body>
</html>
 

tank/templates/tank/tank.html
<!doctype html>
<html>
<head>
<meta charset=utf-8>
</head>
<body>
<h1>戰車小百科</h1>
{% if categories %}
	<h2>戰車分類</h2>
	<table>
		<tr><th>戰車國籍</th><th></th><th></th></tr>
 		{% for category in categories %}
 		<tr>
 			<td>
 			<a href={% url 'tank:category' category.id %}>{{category.name}}</a>
 			</td>
 			<td>
 				<form action={% url 'tank:updateCategory' category.id %}>
 					<input type="submit" value=修改>
 				</form>
 			</td>
 			<td>
 				<form method=post action={% url 'tank:deleteCategory' category.id %}>
 					{% csrf_token %}
 				<input type=submit value=刪除>
 				</form>
			 </td>
 		</tr>
 		{% endfor %}
	</table>
{% else %}
 	<p><strong>目前尚未設定戰車分類</strong></p>
{% endif %}
<p><a href={% url 'tank:addCategory' %}>新增國籍</a></p>
<p><a href={% url 'weapon:weapon' %}>回Weapon網頁</a></p>
</body>
</html>

tank/templates/tank/updateCategory.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>戰車小百科</title>
<meta charset=utf-8>
</head>
<body>

<h1>修改戰車國籍</h1>
<form method=post action={% url 'tank:updateCategory' category.id %}>
 	{% csrf_token %}
 	{{form.as_p}}
 	<input type=submit value=送出>
</form>
<br>
<p><a href={% url 'tank:tank' %}>回 tank 網頁</a></p>
</body>
</html>

tank/templates/tank/updatePage.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>戰車小百科</title>
<meta charset=utf-8>
</head>
<body>

<h1>修改網頁</h1>
<form method=post action={% url 'tank:updatePage' page.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'tank:category' page.category.id %}>回「{{page.category.name}}」網頁
</a></p>

</body>
</html>

weapon/templates/weapon/weapon.html
<!doctype html>
<html>
<head>
<meta charset=utf-8>
</head>
<body>
<h1>武器小百科!</h1>
<p>現在時間：{{now}}</p>
</body>
<p><a href={% url 'tank:tank' %}>前往 Tank 網頁</a></p>
<p><a href={% url 'AH:AH' %}>前往 AH 網頁</a></p>
</html>